
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\anura\Desktop\Programming\programs\DBMS project\ResV1\build\assets\frame3")

custom_font = ("Helvetica", 12, "bold italic") 

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

custom_font = ("Helvetica", 15, "bold italic") 

window = Tk()

window.geometry("775x494")
window.configure(bg = "#FFFFFF")




"""It create GUI on window"""
canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 494,
    width = 775,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    387.0,
    247.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    580.0,
    70.0,
    image=image_image_2
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    430.0,
    243.0,
    image=image_image_4
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    614.0,
    240.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#85433D",
    fg="white",
    font=custom_font,
    highlightthickness=0
)
entry_1.place(
    x=496.0,
    y=223.0,
    width=236.0,
    height=32.0
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=546.0,
    y=300.0,
    width=122.0,
    height=40.1588134765625
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    187.0,
    247.0,
    image=image_image_5
)



window.resizable(False, False)
window.mainloop()