
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage,END,Label


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\anura\Desktop\Programming\programs\DBMS project\ResV1\build\assets\frame1")

custom_font = ("Helvetica", 16, "bold italic") 

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("763x596")
window.configure(bg = "#FFFFFF")








canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 596,
    width = 763,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

label = Label(window, text="", font=custom_font,background="#330000",foreground="white", justify="left")
label.place(x=480,y=120)


def display_text_of_selectefood(stringref):
    global window
    global label
    chgdtext = label.cget("text") + "\n" + stringref
    label.config(text=chgdtext)
    
def clear_display_selected_food():
    label.config(text="")
    

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    381.0,
    300.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    209.0,
    300.0,
    image=image_image_2
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=454.0,
    y=534.0,
    width=280.0,
    height=41.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: display_text_of_selectefood("Cheeseburger"),
    relief="flat"
)
button_2.place(
    x=32.0,
    y=140.0,
    width=168.0,
    height=17.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: display_text_of_selectefood("Cheese Sandwich"),
    relief="flat"
)
button_3.place(
    x=32.0,
    y=157.0,
    width=168.0,
    height=17.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: display_text_of_selectefood("Cheese Sandwich"),
    relief="flat"
)
button_4.place(
    x=32.0,
    y=174.0,
    width=168.0,
    height=17.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: display_text_of_selectefood("Spicy Chicken"),
    relief="flat"
)
button_5.place(
    x=32.0,
    y=191.0,
    width=168.0,
    height=17.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: display_text_of_selectefood("Hot dog"),
    relief="flat"
)
button_6.place(
    x=32.0,
    y=208.0,
    width=168.0,
    height=17.0
)

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: display_text_of_selectefood("Fruit Salad"),
    relief="flat"
)
button_7.place(
    x=223.0,
    y=304.0,
    width=168.0,
    height=17.0
)

button_image_8 = PhotoImage(
    file=relative_to_assets("button_8.png"))
button_8 = Button(
    image=button_image_8,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: display_text_of_selectefood("Cocktail"),
    relief="flat"
)
button_8.place(
    x=223.0,
    y=321.0,
    width=168.0,
    height=17.0
)

button_image_9 = PhotoImage(
    file=relative_to_assets("button_9.png"))
button_9 = Button(
    image=button_image_9,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: display_text_of_selectefood("Nuggets"),
    relief="flat"
)
button_9.place(
    x=223.0,
    y=338.0,
    width=168.0,
    height=17.0
)

button_image_10 = PhotoImage(
    file=relative_to_assets("button_10.png"))
button_10 = Button(
    image=button_image_10,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: display_text_of_selectefood("Sandwich"),
    relief="flat"
)
button_10.place(
    x=223.0,
    y=355.0,
    width=168.0,
    height=17.0
)

button_image_11 = PhotoImage(
    file=relative_to_assets("button_11.png"))
button_11 = Button(
    image=button_image_11,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: display_text_of_selectefood("French Fries"),
    relief="flat"
)
button_11.place(
    x=223.0,
    y=372.0,
    width=168.0,
    height=17.0
)

button_image_12 = PhotoImage(
    file=relative_to_assets("button_12.png"))
button_12 = Button(
    image=button_image_12,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: display_text_of_selectefood("Milk Shake"),
    relief="flat"
)
button_12.place(
    x=31.0,
    y=467.0,
    width=168.0,
    height=17.0
)

button_image_13 = PhotoImage(
    file=relative_to_assets("button_13.png"))
button_13 = Button(
    image=button_image_13,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: display_text_of_selectefood("Iced Tea"),
    relief="flat"
)
button_13.place(
    x=31.0,
    y=484.0,
    width=168.0,
    height=17.0
)

button_image_14 = PhotoImage(
    file=relative_to_assets("button_14.png"))
button_14 = Button(
    image=button_image_14,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: display_text_of_selectefood("Orange juice"),
    relief="flat"
)
button_14.place(
    x=31.0,
    y=501.0,
    width=168.0,
    height=17.0
)

button_image_15 = PhotoImage(
    file=relative_to_assets("button_15.png"))
button_15 = Button(
    image=button_image_15,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: display_text_of_selectefood("Lemon Tea"),
    relief="flat"
)
button_15.place(
    x=31.0,
    y=518.0,
    width=168.0,
    height=17.0
)

button_image_16 = PhotoImage(
    file=relative_to_assets("button_16.png"))
button_16 = Button(
    image=button_image_16,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: display_text_of_selectefood("Coffees"),
    relief="flat"
)
button_16.place(
    x=31.0,
    y=535.0,
    width=168.0,
    height=17.0
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    594.0,
    291.0,
    image=image_image_3
)

button_image_17 = PhotoImage(
    file=relative_to_assets("button_17.png"))
button_17 = Button(
    image=button_image_17,
    borderwidth=0,
    highlightthickness=0,
    command=clear_display_selected_food,
    relief="flat"
)
button_17.place(
    x=454.0,
    y=18.0,
    width=280.0,
    height=38.0
)

canvas.create_rectangle(
    472.0,
    109.0,
    716.0,
    484.0,
    fill="#320000",
    outline="")

button_image_18 = PhotoImage(
    file=relative_to_assets("button_18.png"))
button_18 = Button(
    image=button_image_18,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_18 clicked"),
    relief="flat"
)
button_18.place(
    x=0.0,
    y=4.0,
    width=90.0,
    height=89.0
)


window.resizable(False, False)
window.mainloop()
